name: music_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.2


dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter:  ^10.8.0
  sqlite3: ^2.7.5
  sqlite3_flutter_libs: ^0.5.31
  drift: ^2.25.1
  file_picker: ^9.0.2
  get_it: ^8.0.3
  cupertino_icons: ^1.0.8
  path: ^1.9.0
  path_provider: ^2.1.5
  uuid: ^4.5.1
  watch_it: ^1.6.1
  http: ^1.3.0
  logger: ^2.5.0
  crypto: ^3.0.6
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.25.2
  flutter_launcher_icons: ^0.14.3
  build_runner: ^2.4.14

  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true
