name: Build/release
description: Build and release Electron app
on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        working-directory: ./music_app
        uses: actions/setup-node@v1
        with:
          node-version: 23
          working-directory: ./music_app

      - name: Build/release Electron app
        working-directory: ./music_app
        uses: paneron/action-electron-builder@v1.8.1
        with:
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}